name: x2z-env

channels:
    - conda-forge

dependencies:
    - conda-forge::python=3.10
    - conda-forge::pybind11
    - conda-forge::numpy=1.21.2
    - conda-forge::pytest
    - conda-forge::cmake=3.21.3
    - conda-forge::gcc_linux-64=11.2.0
    - conda-forge::gxx_linux-64=11.2.0
