# cmd: conda build . -c conda-forge
package:
    name: x2z
    version: 0.3.0

source:
    path: .

requirements:
    build:
        - conda-forge::python=3.10
        - conda-forge::pybind11
        - conda-forge::numpy=1.21.2
        - conda-forge::pytest
        - conda-forge::cmake=3.21.3
        - conda-forge::gcc_linux-64=11.2.0
        - conda-forge::gxx_linux-64=11.2.0
    host:
        - conda-forge::python=3.10
    run:
        - conda-forge::python=3.10
        - conda-forge::pybind11
        - conda-forge::numpy=1.21.2
        - conda-forge::pytest
        - conda-forge::cmake=3.21.3
        - conda-forge::gcc_linux-64=11.2.0
        - conda-forge::gxx_linux-64=11.2.0
